<?php

function summary_getStartTime($endTime=NULL)
{
   if(isset($_SESSION['startTime']))
   {
      $startTime = $_SESSION['startTime'];
   }
   else
   {
      if(!$endTime)
      {
         $endTime = time();
      }

      $endYear = date("Y", $endTime);
      $startTime = strtotime(t("January 1 !year", array('!year' => $endYear)));
      $_SESSION['startTime'] = $startTime;
   }

   return $startTime;
}

function summary_getEndTime()
{
   if(isset($_SESSION['endTime']))
   {
      $endTime = $_SESSION['endTime'];
   }
   else
   {
      $endTime = time();
      $_SESSION['endTime'] = $endTime;
   }

   return $endTime;
}

/**
 * Implements hook_help()
 *
 * Displays help and module information
 *
 * @param path
 *    Which path of the site we're using to display help
 * @param arg
 *    Array that holds the current path as returned from arg() function
 */
function summary_help($path, $arg)
{
   switch ($path) 
   {
   case "admin/help#summary":
      return '<p>' . t("Allows a user to view a summary for the budget") . '<\p>';
      break;
   }
}

/**
 * Implements hook_block_info()
 */
function summary_block_info()
{
   $blocks['summary'] = array(
      // The name that will appear in the block list
      'info' => t('Budget Summary'),
   );
   return $blocks;
}


/**
 * Implements hook_block_view()
 *
 * Prepares the contents of the block
 */
function summary_block_view($delta = '')
{
   switch($delta)
   {
   case 'summary':
      $block['subject'] = t('');
      if(user_access('access content'))
      {
         $filterForm = drupal_get_form('summary_filter_form');
         $incomeSummaryForm = drupal_get_form('income_summary_form');
         $budgetSummaryForm = drupal_get_form('budget_summary_form');

         $block['content'] = drupal_render($filterForm);
         setlocale(LC_MONETARY, 'en_US.UTF-8');
         $block['content'] .=  "<h1><b>Total Earned: " . money_format('%.2n', $_SESSION['totalEarned']) . "</b></h1>";
         $block['content'] .= drupal_render($incomeSummaryForm);
         $block['content'] .= "<h1><b>Total Used: " . money_format('%.2n', $_SESSION['totalUsed']) . "</b></h1>";
         $block['content'] .= drupal_render($budgetSummaryForm);
      }

      return $block;
   }
}


/**
 * Function to add the filter form
 */
function summary_filter_form()
{
   $form = array();

   // Create the filter form
   $form['filter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Select Date Range'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
   );

   $endTime = summary_getEndTime();
   $startTime = summary_getStartTime($endTime);

   $startDay = date("j", $startTime);
   $startMonth = date("n", $startTime);
   $startYear = date("Y", $startTime);
   $startDate = array(
      'year' => $startYear,
      'month' => $startMonth,
      'day' => $startDay,
   );
   
   $form['filter']['startDate'] = array(
      '#type' => 'date',
      '#default_value' => $startDate,
      '#title' => t('Start Date'),
   );

   $endDay = date("j", $endTime);
   $endMonth = date("n", $endTime);
   $endYear = date("Y", $endTime);
   $endDate = array(
      'year' => $endYear,
      'month' => $endMonth,
      'day' => $endDay,
   );

   $form['filter']['endDate'] = array(
      '#type' => 'date',
      '#default_value' => $endDate,
      '#title' => t('End Date'),
   );

   $form['filter']['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Save',
      '#submit' => array('summary_filter_submit'),
   );

   $form['filter']['reset'] = array(
      '#type' => 'submit',
      '#value' => 'Reset',
      '#submit' => array('summary_filter_reset'),
   );

   return $form;
}

/**
 * Reset the filter values to the defaults
 */
function summary_filter_reset($form, &$form_state)
{
   $_SESSION['startTime'] = null;
   $_SESSION['endTime'] = null;
}

/**
 * Filter Submit function
 */
function summary_filter_submit($form, &$form_state)
{
   $startYear = $form_state['values']['startDate']['year'];
   $startMonth = $form_state['values']['startDate']['month'];
   $startDay = $form_state['values']['startDate']['day'];
   $startTimeString = $startMonth . "/" . $startDay . "/" . $startYear;
   $startTimestamp = strtotime($startTimeString);

   $endYear = $form_state['values']['endDate']['year'];
   $endMonth = $form_state['values']['endDate']['month'];
   $endDay = $form_state['values']['endDate']['day'];
   $endTimeString = $endMonth . "/" . $endDay . "/" . $endYear;
   $endTimestamp = strtotime($endTimeString);

   $_SESSION['startTime'] = $startTimestamp;
   $_SESSION['endTime'] = $endTimestamp;
}

/**
 * Creates the form to display the income summary
 */
function income_summary_form()
{
   $form = array();

   $endTime = summary_getEndTime();
   $startTime = summary_getStartTime($endTime);

   // Create the summary table form
   $form['incomeSummary'] = array(
      '#type' => 'fieldset',
      '#title' => t('Income Summary for ' . date('n/d/Y', $startTime) . ' to ' . date('n/d/Y', $endTime)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
   );

   $header = array(
      'category' => t('Category'),
      'earned' => t('Amount Earned'),
   );

   $items = array();

   // Retrieve the budget categories from the database
   $incomeContents = budget_income_contents();

   $_SESSION['totalEarned'] = 0;

   setlocale(LC_MONETARY, 'en_US.UTF-8');
   foreach ($incomeContents as $income)
   {
      // Calculate the amount used for the current year
      $amountEarnedQuery = db_select('income', 'i')
         ->fields('i', array('timestamp', 'amount', 'category'))
         ->condition('timestamp', array($startTime, $endTime), 'BETWEEN')
         ->condition('category', $income->id);
      $amountEarnedQuery->addExpression('SUM(amount)', 'sum_of_amount');
      $result = $amountEarnedQuery->execute()->fetchAll();
      $amountEarned = $result[0]->sum_of_amount;

      $items[$income->id] = array(
         'category' => $income->category,
         'earned' => money_format('%.2n', $amountEarned),
      );

      $_SESSION['totalEarned'] = $_SESSION['totalEarned'] + $amountEarned;
   }

   $items[10000] = array(
      'category' => "<b>" . "TOTAL" . "</b>",
      'earned' => "<b>" . money_format('%.2n', $_SESSION['totalEarned']) . "</b>",
   );

   $form['incomeSummary']['items'] = array(
      '#type' => 'tableselect',
      '#header' => $header,
      '#options' => $items,
   );

   return $form;
}

/**
 * Creates the form to display the budget summary
 */
function budget_summary_form()
{
   $form = array();

   $endTime = summary_getEndTime();
   $startTime = summary_getStartTime($endTime);

   // Create the summary table form
   $form['summary'] = array(
      '#type' => 'fieldset',
      '#title' => t('Budget Summary for ' . date('n/d/Y', $startTime) . ' to ' . date('n/d/Y', $endTime)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
   );

   $header = array(
      'category' => t('Category'),
      'allocated' => t('Amount Allocated'),
      'used' => t('Amount Used'),
      'remaining' => t('Percent Remaining'),
   );

   $items = array();

   // Retrieve the budget categories from the database
   $budgetContents = budget_contents();

   $totalAllocated = 0;
   $_SESSION['totalUsed'] = 0;

   setlocale(LC_MONETARY, 'en_US.UTF-8');
   foreach ($budgetContents as $budget)
   {
      // Calculate the amount used for the current year
      $amountUsedQuery = db_select('transactions', 't')
         ->fields('t', array('timestamp', 'amount', 'category'))
         ->condition('timestamp', array($startTime, $endTime), 'BETWEEN')
         ->condition('category', $budget->id);
      $amountUsedQuery->addExpression('SUM(amount)', 'sum_of_amount');
      $result = $amountUsedQuery->execute()->fetchAll();
      $amountUsed = $result[0]->sum_of_amount;
      $remaining = round((($budget->allocation - $amountUsed) / $budget->allocation) * 100);

      $items[$budget->id] = array(
         'category' => $budget->category,
         'allocated' => money_format('%.2n', $budget->allocation),
         'used' => money_format('%.2n', $amountUsed),
         'remaining' => $remaining,
      );

      $totalAllocated = $totalAllocated + $budget->allocation;
      $_SESSION['totalUsed'] = $_SESSION['totalUsed'] + $amountUsed;
   }

   $items[10000] = array(
      'category' => "<b>" . "TOTAL" . "</b>",
      'allocated' => "<b>" . money_format('%.2n', $totalAllocated) . "</b>",
      'used' => "<b>" . money_format('%.2n', $_SESSION['totalUsed']) . "</b>",
      'remaining' => "<b>" . round((($totalAllocated - $_SESSION['totalUsed']) / $totalAllocated) * 100) . "<b>",
   );

   $form['summary']['items'] = array(
      '#type' => 'tableselect',
      '#header' => $header,
      '#options' => $items,
   );

   return $form;
}
