<?php

/**
 * Implements hook_schema()
 */
function income_schema()
{
   $schema['income'] = array(
      'description' => t('The base table for income'),
      'fields' => array(
         'id' => array(
            'description' => 'The primary identifier for an income transaction',
            'type' => 'serial',
            'unsigned' => TRUE,
            'not null' => TRUE
         ),
         'uid' => array(
            'description' => 'ID for the user that entered this income transaction',
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => TRUE
         ),
         'timestamp' => array(
            'description' => 'Timestamp for the income transaction in seconds',
            'type' => 'int',
            'not null' => TRUE,
         ),
         'amount' => array(
            'description' => 'Value of the income transaction',
            'type' => 'float',
            'not null' => TRUE,
         ),
         'category' => array(
            'description' => 'Category for the transaction',
            'type' => 'varchar',
            'length' => 100,
            'not null' => TRUE,
         ),
      ),
      'primary key' => array('id'),
   );

   return $schema;
}

/**
 * Implements hook_help()
 *
 * Displays help and module information
 *
 * @param path
 *    Which path of the site we're using to display help
 * @param arg
 *    Array that holds the current path as returned from arg() function
 */
function income_help($path, $arg)
{
   switch ($path) 
   {
   case "admin/help#income":
      return '<p>' . t("Allows a user to enter income transactions for the budget") . '<\p>';
      break;
   }
}

/**
 * Implements hook_block_info()
 */
function income_block_info()
{
   $blocks['income'] = array(
      // The name that will appear in the block list
      'info' => t('Income'),
   );
   return $blocks;
}


/**
 * Custom content function
 * Retrieve the transactions spanning the date range provided
 */
function income_contents($startTime, $endTime)
{
   // Select the transactions from the transactions table
   $query = db_select('income', 't')
      ->fields('t', array('id', 'uid', 'timestamp', 'amount', 'category'))
      ->condition('timestamp', array($startTime, $endTime), 'BETWEEN')
      ->orderby('timestamp', 'DESC')
      ->execute();

   return $query;
}

/**
 * Implements hook_block_view()
 *
 * Prepares the contents of the block
 */
function income_block_view($delta = '')
{
   switch($delta)
   {
   case 'income':
      $block['subject'] = t('');
      if(user_access('access content'))
      {
         $addIncomeForm = drupal_get_form('income_add_form');
         $block['content'] = drupal_render($addIncomeForm);

         $numResults = db_select('income', 't')
            ->fields('t', array('id'))
            ->countQuery()
            ->execute()
            ->fetchField();

         if($numResults > 0)
         {
            $filterForm = drupal_get_form('income_filter_form');
            $viewIncomeForm = drupal_get_form('income_view_form');
            $block['content'] .= drupal_render($filterForm);
            $block['content'] .= drupal_render($viewIncomeForm);
         }
      }

      return $block;
   }
}

/**
 * Returns the category select array to add in forms
 */
function getIncomeCategorySelect($defaultCategory)
{
   $categorySelect = array();

   // Get the budget contents from the database
   $result = budget_income_contents();

   // Array to contain the list of categories returned from the database
   $categories = array();

   foreach($result as $income)
   {
      $categories[$income->id] = $income->category;
   }

   if(count($categories))
   {
      if(empty($defaultCategory))
      {
         $categorySelect = array(
            '#type' => 'select',
            '#title' => t('Category'),
            '#options' => $categories,
         );
      }
      else
      {
         // TODO: default_value does not work as called from transactions_view_form
         $categorySelect = array(
            '#type' => 'select',
            '#title' => t('Category'),
            '#options' => $categories,
            '#default_value' => $defaultCategory
         );
      }
   }

   return $categorySelect;
}

/**
 * Creates the form to add a transaction
 */
function income_add_form()
{
   $form = array();

   $categorySelect = getIncomeCategorySelect(array());

   if(!empty($categorySelect))
   {
      // Create the addIncome form
      $form['addIncome'] = array(
         '#type' => 'fieldset',
         '#title' => t('Add a new income transaction'),
         '#collapsible' => TRUE,
         '#collapsed' => FALSE,
      );

      $form['addIncome']['amount'] = array(
         '#type' => 'textfield',
         '#title' => t('Amount'),
         '#size' => 40,
         '#maxLength' => 40,
      );

      $form['addIncome']['date'] = array(
         '#type' => 'date',
         '#title' => t('Date'),
      );

      $form['addIncome']['categorySelect'] = $categorySelect;

      $form['addIncome']['submit'] = array(
         '#type' => 'submit',
         '#value' => 'Add Income Transaction',
         '#validate' => array('add_income_validate'),
         '#submit' => array('add_income_submit'),
      );
   }
   else
   {
      drupal_set_message(t('Add at least one budget income category in order to add a transaction'), 'error');
   }

   return $form;
}

function add_income_validate($form, &$form_state)
{
   $amount = str_replace('$', '', $form_state['values']['amount']);
   $year = $form_state['values']['date']['year'];
   $month = $form_state['values']['date']['month'];
   $day = $form_state['values']['date']['day'];
   $categoryId = $form_state['values']['categorySelect'];

   if(!$amount)
   {
      form_set_error('amount', 'Please enter the amount for the transaction');
   }

   if(!$year || !$month || !$day)
   {
      form_set_error('date', 'Please enter a valid date for the transaction');
   }

   if(!$categoryId)
   {
      form_set_error('categorySelect', 'Please select a category for the transaction');
   }

   // Validate that the date selected is not in the future
   $currentYear = intval(date("Y"));
   $currentMonth = intval(date("m"));
   $currentDay = intval(date("d"));
   if($currentYear < $year)
   {
      form_set_error('date][year', 'Date cannot be in the future');
   }
   else if($currentYear == $year)
   {
      if($currentMonth < $month)
      {
         form_set_error('date][month', 'Date cannot be in the future');
      }
      else if($currentMonth == $month)
      {
         if($currentDay < $day)
         {
            form_set_error('date][day', 'Date cannot be in the future');
         }
      }
   }

   // Validate the amount is formatted properly
   if(preg_match('/^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?$/', $amount) != 1)
   {
      form_set_error('amount', 'Please enter a valid transaction amount');
   }

   // Validate that the category id is in the database
   if($categoryId)
   {
      $result = db_select('budgetIncome', 'b')
         ->fields('b')
         ->condition('id', $categoryId)
         ->execute()
         ->fetchField();

      if(empty($result))
      {
         form_set_error('categorySelect', t("Select a valid category"));
      }
   }
}

function add_income_submit($form, &$form_state)
{
   global $user;
   $amount = str_replace('$', '', $form_state['values']['amount']);
   $amount = preg_replace("/([^0-9\\.])/i", "", $amount);
   $year = $form_state['values']['date']['year'];
   $month = $form_state['values']['date']['month'];
   $day = $form_state['values']['date']['day'];
   $timeString = $month . "/" . $day . "/" . $year;
   $timestamp = strtotime($timeString);

   $categoryId = $form_state['values']['categorySelect'];

   if(db_insert('income')
      ->fields(array(
         'uid' => $user->uid,
         'timestamp' => $timestamp,
         'amount' => $amount,
         'category' => $categoryId
      ))
      ->execute())
   {
      setlocale(LC_MONETARY, 'en_US.UTF-8');
      $debug_message = "Successfully added income: for " . money_format('%.2n', $amount) . " on " . $month . "/" . $day . "/" . $year . "  seconds " . $timestamp;
      drupal_set_message($debug_message, 'status');
   }
}


/**
 * Function to add the view transactions form
 */
function income_filter_form()
{
   $form = array();

   // Create the filter form
   $form['filter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Filter Transactions'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
   );

   // Get the current time
   $endTime = time();
   if(isset($_SESSION['incomeEndTime']))
   {
      // Read the session variable into the current time
      $endTime = $_SESSION['incomeEndTime'];
   }
   else
   {
      // Save the endTime to the current time
      $_SESSION['incomeEndTime'] = $endTime;
   }

   $endDay = date("d", $endTime);
   $endMonth = date("n", $endTime);
   $endYear = date("Y", $endTime);
   $endDate = array(
      'year' => $endYear,
      'month' => $endMonth,
      'day' => $endDay,
   );

   // Get the default start time
   // Seconds in 30 Days = (60 sec) * (60 min) * (24 hours) * (30 days)
   $startTime = strtotime(t("January 1 !year", array('!year' => $endYear)));
   if(isset($_SESSION['incomeStartTime']))
   {
      $startTime = $_SESSION['incomeStartTime'];
   }
   else
   {
      $_SESSION['incomeStartTime'] = $startTime;
   }

   $startDay = date("d", $startTime);
   $startMonth = date("n", $startTime);
   $startYear = date("Y", $startTime);
   $startDate = array(
      'year' => $startYear, 
      'month' => $startMonth, 
      'day' => $startDay
   );

   $form['filter']['startDate'] = array(
      '#type' => 'date',
      '#default_value' => $startDate,
      '#title' => t('Start Date'),
   );

   $form['filter']['endDate'] = array(
      '#type' => 'date',
      '#default_value' => $endDate,
      '#title' => t('End Date'),
   );

   $form['filter']['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Filter',
      '#submit' => array('income_filter_submit'),
   );

   return $form;
}

function income_filter_submit($form, &$form_state)
{
   $startYear = $form_state['values']['startDate']['year'];
   $startMonth = $form_state['values']['startDate']['month'];
   $startDay = $form_state['values']['startDate']['day'];
   $startTimeString = $startMonth . "/" . $startDay . "/" . $startYear;
   $startTimestamp = strtotime($startTimeString);
   $_SESSION['incomeStartTime'] = $startTimestamp;

   $endYear = $form_state['values']['endDate']['year'];
   $endMonth = $form_state['values']['endDate']['month'];
   $endDay = $form_state['values']['endDate']['day'];
   $endTimeString = $endMonth . "/" . $endDay . "/" . $endYear;
   $endTimestamp = strtotime($endTimeString);
   $_SESSION['incomeEndTime'] = $endTimestamp;
}

/**
 * Function to add the view transactions form
 */
function income_view_form()
{
   // Get the end time from the session variable
   $endTime = time();
   if(isset($_SESSION['incomeEndTime']))
   {
      // Read the session variable into the current time
      $endTime = $_SESSION['incomeEndTime'];
   }
   else
   {
      // Save the endTime to the current time
      $_SESSION['incomeEndTime'] = $endTime;
   }

   $endDay = date("d", $endTime);
   $endMonth = date("n", $endTime);
   $endYear = date("Y", $endTime);
   $endDate = array(
      'year' => $endYear,
      'month' => $endMonth,
      'day' => $endDay,
   );

   // Get the start time from the session variable
   // Seconds in 30 Days = (60 sec) * (60 min) * (24 hours) * (30 days)
   $startTime = strtotime(t("January 1 !year", array('!year' => $endYear)));
   if(isset($_SESSION['incomeStartTime']))
   {
      $startTime = $_SESSION['incomeStartTime'];
   }
   else
   {
      $_SESSION['incomeStartTime'] = $startTime;
   }

   // Get the transactions from the database
   $result = income_contents($startTime, $endTime);

   // Array to contain the list of transactions returned from the database
   $income = array();

   // TODO: REMOVE when getIncomeCategorySelect works here
   // Get the budget contents from the database
   $budgetContents = budget_income_contents();

   // Array to contain the list of categories returned from the database
   $categories = array();

   foreach($budgetContents as $budgetIncome)
   {
      $categories[$budgetIncome->id] = $budgetIncome->category;
   }
   // TODO: END REMOVE
   
   // Iterate over the result set and set the options for the tableselect
   setlocale(LC_MONETARY, 'en_US.UTF-8');
   foreach($result as $incomeEntry)
   {
      $income[$incomeEntry->id] = array(
         'amount' => t("!amount", array('!amount' => money_format('%.2n', $incomeEntry->amount))),
         'date' => date('m/d/Y', $incomeEntry->timestamp),
         'category' => $categories[$incomeEntry->category],
         /* TODO: Does not render properly. default_value is ignored
         'category' => array(
            'data' => getIncomeCategorySelect($transaction->category)
         )
          */
      );
   }

   $form = array();

   // Create the transactions table form
   if(!empty($income))
   {
      $form['income'] = array(
         '#type' => 'fieldset',
         '#title' => t('Income'),
         '#collapsible' => TRUE,
         '#collapsed' => empty($income)
      );

      $header = array(
         'amount' => t('Amount'),
         'date' => t('Date'),
         'category' => t('Category'),
      );

      $form['income']['items'] = array(
         '#type' => 'tableselect',
         '#header' => $header,
         '#options' => $income,
         '#multiple' => TRUE,
      );

      $form['income']['remove'] = array(
         '#type' => 'submit',
         '#value' => 'Delete Selected',
         '#submit' => array('remove_income_submit'),
      );
   }

   return $form;
}

function remove_income_submit($form, &$form_state)
{
   $debug_message = t('');
   $selectedIDs = array_filter($form_state['values']['items']);

   $num_deleted = 0;

   foreach($selectedIDs as $key => $value)
   {
      if($value)
      {
         $num_deleted += db_delete('income')
            ->condition('id', $key)
            ->execute();
      }
   }

   if($num_deleted > 0)
   {
      $debug_message .= "Successfully removed " . $num_deleted . " income<br/>";
      drupal_set_message($debug_message, 'status');
   }
}

